
CREATE TABLE IF NOT EXISTS USUARIO (
    ID_USUARIO INT(8) NOT NULL AUTO_INCREMENT,NOME VARCHAR(45),CONTATOS VARCHAR(45),
    ID_DADOS_DE_USUARIO integer, ID_PERFIL integer,PRIMARY KEY (ID_USUARIO) );
CREATE TABLE IF NOT EXISTS DADOS_DE_USUARIO (
    ID_DADOS_DE_USUARIO INT NOT NULL AUTO_INCREMENT,SENHA INT(12),NOME VARCHAR(45),TELEFONE INT(11),
    EMAIL VARCHAR(45),IDADE INT(2), CPF INT(11),ENDERECO VARCHAR(115),ID_USUARIO integer,
    PRIMARY KEY (ID_DADOS_DE_USUARIO));
CREATE TABLE IF NOT EXISTS PERFIL (
     ID_PERFIL INT(8) NOT NULL AUTO_INCREMENT,ID_USUARIO integer, ID_POST integer, ID_GOSTOS  integer,FOTO LONGBLOB NOT NULL,
     PRIMARY KEY (ID_PERFIL));
CREATE TABLE IF NOT EXISTS TIPTRAVEL (ID_TIPTRAVEL INT NOT NULL AUTO_INCREMENT,EMAIL VARCHAR(45),TELEFONE INT(11),
ENDERECO VARCHAR(115),DESCRICAO VARCHAR(45),
PRIMARY KEY (ID_TIPTRAVEL));
CREATE TABLE IF NOT EXISTS POST(ID_POST INT NOT NULL AUTO_INCREMENT,DESCRICAO VARCHAR(45),IMAGEM LONGBLOB NOT NULL,
ID_SERVICO integer,
ID_PERFIL integer, PRIMARY KEY (ID_POST));
CREATE TABLE IF NOT EXISTS GOSTOS(ID_GOSTOS INT NOT NULL AUTO_INCREMENT,DESCRICAO VARCHAR(45),
    ID_PERFIL integer, PRIMARY KEY (ID_GOSTOS));
CREATE TABLE IF NOT EXISTS FEED( ID_POST integer,ID_GOSTOS integer,ID_PARCEIROS integer);
CREATE TABLE IF NOT EXISTS AMIGOS (ID_AMIGOS INT(8) NOT NULL AUTO_INCREMENT,ID_PERFIL integer,ID_AMIGO integer,PRIMARY KEY (ID_AMIGOS) );
CREATE TABLE IF NOT EXISTS NOTIFICACAO (ID_NOTIFICACAO INT(8) NOT NULL AUTO_INCREMENT,ID_PARA integer,ID_DE integer,TIPO VARCHAR(45),
PRIMARY KEY (ID_NOTIFICACAO) );

-- ALTERANDO TABELAS E ADICIONANDO CHAVES EXTRANGEIRAS:

ALTER TABLE DADOS_DE_USUARIO ADD CONSTRAINT FK_USUARIO_ID_DADOSUSUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO) ;

ALTER TABLE USUARIO ADD  CONSTRAINT FK_ID_USUARIODADOS_DE_USUARIO FOREIGN KEY (ID_DADOS_DE_USUARIO) REFERENCES DADOS_DE_USUARIO (ID_DADOS_DE_USUARIO);

ALTER TABLE PERFIL ADD   CONSTRAINT FK_ID_PERFILUSUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO);

ALTER TABLE USUARIO ADD   CONSTRAINT FK_ID_USUARIOPERFIL FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL (ID_PERFIL);

ALTER TABLE PERFIL ADD  CONSTRAINT FK_ID_PERFILPOST FOREIGN KEY (ID_POST) REFERENCES POST (ID_POST);

ALTER TABLE GOSTOS ADD  CONSTRAINT FK_ID_GOSTOSPERFIL FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL (ID_PERFIL);

ALTER TABLE PERFIL ADD  CONSTRAINT FK_ID_PERFILGOSTOS FOREIGN KEY (ID_GOSTOS) REFERENCES GOSTOS (ID_GOSTOS);

ALTER TABLE FEED ADD  CONSTRAINT FK_ID_FEEDPOST FOREIGN KEY (ID_POST) REFERENCES POST (ID_POST);

ALTER TABLE FEED ADD  CONSTRAINT FK_ID_FEEDGOSTOS FOREIGN KEY (ID_GOSTOS) REFERENCES  GOSTOS (ID_GOSTOS);

ALTER TABLE POST ADD  CONSTRAINT FK_ID_POSTPERFIL FOREIGN KEY (ID_PERFIL) REFERENCES  PERFIL(ID_PERFIL);

ALTER TABLE AMIGOS ADD  CONSTRAINT FK_ID_AMIGOSPERFIL FOREIGN KEY (ID_PERFIL) REFERENCES  PERFIL(ID_PERFIL);

ALTER TABLE AMIGOS ADD  CONSTRAINT FK_ID_AMIGOPERFIL FOREIGN KEY (ID_AMIGO) REFERENCES  PERFIL(ID_PERFIL);

ALTER TABLE NOTIFICACAO ADD  CONSTRAINT FK_ID_NOTIDADOS_DE_USUARIO FOREIGN KEY (ID_PARA) REFERENCES DADOS_DE_USUARIO (ID_DADOS_DE_USUARIO);

ALTER TABLE NOTIFICACAO ADD  CONSTRAINT FK_ID_NOTIDADOS_DE_USUARIO_DE FOREIGN KEY (ID_DE) REFERENCES DADOS_DE_USUARIO (ID_DADOS_DE_USUARIO);
